### ISSUE TITLE
Provide teacher pretrained for project

### ISSUE THREAD

**Issue by vietnvri** [RicherMans/Datadriven-GPVAD#15]
Thanks for the great work!
Can you provide two teachers pretrained balanced.pth and balanced_binary.pth?

I appreciate your help!

**Comment by RicherMans** [comment]
Hey there,
I guess these two are entirely absolute for most people, since their performance is just far worse than any teacher provided in this repo.
Nonetheless, you can find them [here](https://github.com/RicherMans/GPV/tree/master/pretrained), where [gpv_b.pth](https://github.com/RicherMans/GPV/blob/master/pretrained/gpv_b.pth) is the balanced_binary teacher and [gpv_f.pth](https://github.com/RicherMans/GPV/blob/master/pretrained/gpv_f.pth) is the balanced teacher.

I just wanna emphasize that I strongly recommend using the SRE pretrained teacher for English VAD and C1 for Chinese.
